export const hotelData = [
  {
    name: 'Catalonia Atenas',
    stars: 5,
    price: {
      amount: 72,
      discountedAmount: 48,
      currency: '$',
      discountType: 'Special Discount',
      totalPrice: 240,
    },
    images: [
      '/images/hotel-1.jpg',
      '/images/hotel-1.jpg',
      '/images/hotel-1.jpg',
      '/images/hotel-1.jpg',
      '/images/hotel-1.jpg',
    ],
    rating: { value: 4.8, count: 5 },
    reviews: 167,
    location: 'Near Sagrada Familia',
    checkIn: '14:00',
    checkOut: '12:00',
    freeCancellation: true,
    roomType: ['Double Room', 'Twin Room'],
  },
  {
    name: 'Hesperia Barcelona Del Mar',
    stars: 3,
    price: {
      amount: 72,
      discountedAmount: 48,
      currency: '$',
      discountType: 'Special Discount',
      totalPrice: 240,
    },
    images: [
      '/images/hesperia-barcelona.jpg',
      '/images/hesperia-barcelona.jpg',
      '/images/hesperia-barcelona.jpg',
      '/images/hesperia-barcelona.jpg',
      '/images/hesperia-barcelona.jpg',
    ],
    rating: { value: 3.9, count: 5 },
    reviews: 129,
    location: 'Near Poblenou Metro Station',
    checkIn: '14:00',
    checkOut: '12:00',
    freeCancellation: false,
    roomType: ['Double Room', 'Twin Room'],
  },
];
